/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.zj68.battleship;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintStream;
import java.io.Reader;

import org.w3c.dom.Text;

public class App {
  private final TextPlayer player1;
  private final TextPlayer player2;

  public App(TextPlayer p1, TextPlayer p2) {
    this.player1 = p1;
    this.player2 = p2;
  }
  public void doPlacementPhase() throws IOException{
    player1.doPlacementPhase();
    player2.doPlacementPhase();
  }
  public void doGame() throws IOException {
    while(true) {
      player1.playOneTurnWithActions(player2.theBoard, player2.view, player2.name);
       if (player2.theBoard.checkLose()) {
        player2.out.println("Player "+player1.name+" wins!");
        break;
      }
       player2.playOneTurnWithActions(player1.theBoard, player1.view, player1.name);
       if (player1.theBoard.checkLose()) {
        player1.out.println("Player "+player2.name+" wins!");
        break;
      }
    }
  }
  
  public static void main(String[] args) throws IOException{
    Board<Character> b1 = new BattleShipBoard<>(10, 20,'X');
    Board<Character> b2 = new BattleShipBoard<>(10, 20,'X');
    BufferedReader input = new BufferedReader(new InputStreamReader(System.in));
    V2ShipFactory factory = new V2ShipFactory();
    TextPlayer p1 = new TextPlayer("A",b1, input, System.out,factory);
    TextPlayer p2 = new TextPlayer("B", b2, input, System.out, factory);
    App app = new App(p1, p2);
    app.doPlacementPhase();
    app.doGame();;
    }
}
