/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.zj68.battleship;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintStream;
import java.io.Reader;

public class App {
  private final Board<Character> theBoard;
  private final BoardTextView view;
  private final BufferedReader inputReader;
  private final PrintStream out;
  private final AbstractShipFactory<Character> shipFactory;

  public App(Board<Character> theBoard,Reader inputSource,PrintStream out) {
    this.theBoard = theBoard;
    this.view = new BoardTextView(theBoard);
    this.inputReader = new BufferedReader(inputSource);
    this.out = out;
    this.shipFactory = new V1ShipFactory();
  }
  public Placement readPlacement(String prompt) throws IOException {
    out.println(prompt);
    String s = inputReader.readLine();
    return new Placement(s);
  }
  public void doOnePlacement() throws IOException {
    Placement toPlace = readPlacement("Where would you like to put your ship?");
    Ship<Character> s = shipFactory.makeDestroyer(toPlace);
    theBoard.tryAddShip(s);
    out.println(view.displayMyOwnBoard());
  }
  /*public String getGreeting() {
    return "Hello World!";
    }*/

  public static void main(String[] args) throws IOException{
    Board<Character> b = new BattleShipBoard<Character>(10, 20);
    App app = new App(b,new InputStreamReader(System.in),System.out);
    app.doOnePlacement();
    //System.out.println(new App().getGreeting());
    }
}
